### PR TITLE
Skip interfaces not publicly accessible in authoring scenarios

### LINKED ISSUE #1369: WinRTTypeWriter generator fails with NullReferenceException
**Describe the bug**

It seems there's a NRE bug in the "WinRTTypeWriter" generator, at least in some scenarios.
Might be fixed already with all the changes in the AOT branch, but figured I'd report just for tracking 🙂

**To Reproduce**

1. Checkout to https://github.com/Sergio0694/ComputeSharp/commit/79ff77b3a1dd10affc7ee6047b9935a98f85a96d
2. Build the `ComputeSharp.NativeLibrary.WinRT` project

It's failing for me both when building from VS and when trying to build with `msbuild` from a developer command prompt.

> CSC : error CS8785: Generator 'SourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'NullReferenceException' with message 'Object reference not set to an instance of an object.'.

```
Error	CS8785	Generator 'SourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'NullReferenceException' with message 'Object reference not set to an instance of an object.'.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Generator.WinRTTypeWriter.QualifiedName(ISymbol symbol, Boolean includeGenerics)
   at Generator.WinRTTypeWriter.EncodeSymbol(Symbol symbol, SignatureTypeEncoder typeEncoder)
   at Generator.WinRTTypeWriter.EncodeParameters(Parameter[] parameters, ParametersEncoder parametersEncoder)
   at Generator.WinRTTypeWriter.<>c__DisplayClass65_0.<AddMethodReference>b__1(ParametersEncoder parametersEncoder)
   at System.Reflection.Metadata.Ecma335.MethodSignatureEncoder.Parameters(Int32 parameterCount, Action`1 returnType, Action`1 parameters)
   at Generator.WinRTTypeWriter.AddMethodReference(String name, Parameter[] parameters, Symbol returnSymbol, INamedTypeSymbol parentType, Boolean isStatic)
   at Generator.WinRTTypeWriter.AddMethodReference(IMethodSymbol method)
   at Generator.WinRTTypeWriter.AddProjectedType(INamedTypeSymbol type, String projectedTypeOverride)
   at Generator.WinRTTypeWriter.AddType(INamedTypeSymbol type, Boolean treatAsProjectedType)
   at Generator.WinRTTypeWriter.FinalizeGeneration()
   at Generator.ComponentGenerator.Generate()
   at Generator.SourceGenerator.Execute(GeneratorExecutionContext context)
   at Microsoft.CodeAnalysis.SourceGeneratorAdaptor.<Initialize>b__5_5(SourceProductionContext productionContext, GeneratorContextBuilder contextBuilder)
   at Microsoft.CodeAnalysis.UserFunctionExtensions.<>c__DisplayClass3_0`2.<WrapUserAction>b__0(TInput1 input1, TInput2 input2, CancellationToken token)Active	

```

**Expected behavior**

Project should build correctly.

**Version Info**
- net8.0-windows10.0.22621.0
- CsWinRT 2.0.4

### PR DESCRIPTION
**Pull request by Sergio0694**
### Overview

This PR updates the WinRT authoring generator to skip interfaces that are not publicly accessible.

### CODE REVIEW

File: src/Tests/AuthoringTest/Program.cs [hunk 1]
```diff
@@ -1569,4 +1574,140 @@ public partial struct PartialStruct
...
+                lpVtbl->GetNumber = &GetDeviceFromAbi;
+
+                return (IntPtr)lpVtbl;
+            }
+
+            private IUnknownVftbl IUnknownVftbl;
+            private delegate* unmanaged[Stdcall]<void*, int*, int> GetNumber;
+
+            [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
+            private static int GetDeviceFromAbi(void* thisPtr, int* value)
```
Comment (manodasanW) [inline src/Tests/AuthoringTest/Program.cs:1632]: nit: was this here and below supposed to be GetNumberFromAbi rather than GetDvice.

File: src/Authoring/WinRT.SourceGenerator/WinRTTypeWriter.cs [hunk 2]
```diff
@@ -2683,12 +2707,19 @@ static bool IsWinRTType(ISymbol symbol)
...
-                type is IPropertySymbol property && !property.ExplicitInterfaceImplementations.IsDefaultOrEmpty ||
-                type is IEventSymbol @event && !@event.ExplicitInterfaceImplementations.IsDefaultOrEmpty;
+            // Check that the type has either public accessibility, or is an explicit interface implementation
+            if (symbol.DeclaredAccessibility == Accessibility.Public ||
+                symbol is IMethodSymbol method && !method.ExplicitInterfaceImplementations.IsDefaultOrEmpty ||
+                symbol is IPropertySymbol property && !property.ExplicitInterfaceImplementations.IsDefaultOrEmpty ||
+                symbol is IEventSymbol @event && !@event.ExplicitInterfaceImplementations.IsDefaultOrEmpty)
+            {
+                // If we have a containing type, we also check that it's publicly accessible
+                return symbol.ContainingType is not { } containingType || containingType.IsPubliclyAccessible();
```
Comment (manodasanW) [inline src/Authoring/WinRT.SourceGenerator/WinRTTypeWriter.cs:2719]: I am trying to understand this, should this have been an `&&` rather than a `||`  or am I misunderstanding what is not {} does.

**Review by manodasanW — APPROVED** [review]

File: src/Tests/AuthoringTest/Program.cs (hunk 1 above)
Comment (Sergio0694) [reply src/Tests/AuthoringTest/Program.cs]: Oops, yes, leftover from ComputeSharp, fixed! 🙂

File: src/Authoring/WinRT.SourceGenerator/WinRTTypeWriter.cs (hunk 2 above)
Comment (Sergio0694) [reply src/Authoring/WinRT.SourceGenerator/WinRTTypeWriter.cs:2719]: So, `is not { }` matches if the expression is not an instance (it's like `is null`, but also declares a local). So:
- If `containingType` is `null`, return `true`
- Otherwise (ie. `containingType != null`), return `true` if it's publicly accessible

If we used `&&`, we'd be trying to access `containingType` when the first expression already matched, but if that's the case, then `containingType` is not defined (because the expression matches on `is not`). In fact, if you changed it to `&&`, the code would just not compile, as `containingType` would be uninitialized in that case 🙂
