### PR TITLE
Return IIDOptimizer exit code

### LINKED ISSUE #953: IID Optimizer writes zero byte patched DLL on exception
If the optimizer throws an exception, it corrupts the patched DLL, writing zero bytes.  Workaround is to disable optimization via CsWinRTIIDOptimizerOptOut.

Build log excerpt from a recent WinUI build follows:

2021-08-04T22:12:11.9946856Z CsWinRTInvokeGuidPatcher:
2021-08-04T22:12:11.9947992Z   "C:\a\1\s\packages\microsoft.windows.cswinrt\1.3.3\build\tools\IIDOptimizer\IIDOptimizer.exe" @"C:\a\1\s\BuildOutput\obj\x86chk\controls\test\MUXControlsTestApp\TAEF.Desktop\MUXControlsTestApp.TAEF.Desktop\net5.0-windows10.0.18362.0\win10-x86\IIDOptimizer\cswinrt_iidoptimizer.rsp"
2021-08-04T22:12:11.9958642Z   "C:\a\1\s\packages\microsoft.windows.cswinrt\1.3.3\build\tools\IIDOptimizer\IIDOptimizer.exe" @"C:\a\1\s\BuildOutput\obj\x86chk\controls\test\MUXControlsTestApp\TAEF.Desktop\MUXControlsTestApp.TAEF.Desktop\net5.0-windows10.0.18362.0\win10-x86\IIDOptimizer\cswinrt_iidoptimizer.rsp"
2021-08-04T22:12:12.8969155Z   Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
2021-08-04T22:12:12.8970165Z    ---> Mono.Cecil.ResolutionException: Failed to resolve Microsoft.UI.Xaml.Controls.ScrollingInteractionState
2021-08-04T22:12:12.8970875Z      at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
2021-08-04T22:12:12.8971497Z      at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
2021-08-04T22:12:12.8972168Z      at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
2021-08-04T22:12:12.8972865Z      at Mono.Cecil.MetadataBuilder.AddField(FieldDefinition field)
2021-08-04T22:12:12.8973443Z      at Mono.Cecil.MetadataBuilder.AddFields(TypeDefinition type)
…
2021-08-04T22:12:12.9241771Z CsWinRTReplaceForPatchedRuntime:
2021-08-04T22:12:12.9243130Z   Copying file from "C:\a\1\s\BuildOutput\obj\x86chk\controls\test\MUXControlsTestApp\TAEF.Desktop\MUXControlsTestApp.TAEF.Desktop\net5.0-windows10.0.18362.0\win10-x86\IIDOptimizer\MUXControlsTestApp.TAEF.Desktop.dll" to "C:\a\1\s\BuildOutput\obj\x86chk\controls\test\MUXControlsTestApp\TAEF.Desktop\MUXControlsTestApp.TAEF.Desktop\net5.0-windows10.0.18362.0\win10-x86\MUXControlsTestApp.TAEF.Desktop.dll".

### PR DESCRIPTION
**Pull request by j0shuams**
This PR corrects an error in the iidoptimizer where the intended exit codes were forgotten on termination. Given that we have a helper for resolving winrt.runtime, I made sure we exit early if anything goes wrong. 

Fixes #953

### CODE REVIEW

File: src/Perf/IIDOptimizer/Program.cs [hunk 1]
```diff
@@ -133,6 +141,12 @@ private static int GuidPatch(string targetAssembly, string outputDirectory, IEnu
                 Console.WriteLine($"\tAssembly : {e.AssemblyReference.Name}"); 
                 return -1; 
             }
+            catch (Exception e)
+            {
+                Console.WriteLine("Application failed with unexpected exception.");
```
Comment (manodasanW) [inline src/Perf/IIDOptimizer/Program.cs:146]: Consider removing Application for consistency with the other messages.

**Review by manodasanW — APPROVED** [review]

File: src/Perf/IIDOptimizer/Program.cs (hunk 1 above)
Comment (j0shuams) [reply src/Perf/IIDOptimizer/Program.cs]: Good point, we should be consistent
