### PR TITLE
Fixing scenarios where default interface isn't passed for custom projections and perf improvements

### LINKED ISSUE #360: MarshalInterface.FromAbi doesn't handle case where ptr isn't the default interface
MarshalInterface.FromAbi calls MarshalInspectable.FromAbi which checks the runtimeclass and calls FromAbi on it which assumes the ptr is for the default interface.  But it can be for another interface such as IStringable.  This then ends up calling the wrong function in some cases as vtable is wrong.

Array_Stringable_Call test will repro the issue if you undo the temporary fix put in for that instance https://github.com/microsoft/CsWinRT/blob/631bb364e79139c33296e47a8622052ab0b66259/WinRT.Runtime/Projections/Uri.cs#L134

ObjectReference<IUnknownVftbl>.FromAbi(ptr).As<ABI.Windows.Foundation.IUriRuntimeClassVftbl>(); -> ObjectReference<ABI.Windows.Foundation.IUriRuntimeClassVftbl>.FromAbi(ptr);

Ensure that fixes for these don't regress:
- [ ] #410 
- [ ] #362

### PR DESCRIPTION
**Pull request by manodasanW**
- If the default interface wasn't passed for custom projections, like IStringable for URI, you can end up in crashes or unexpected results.  This PR addresses it by making MarshalInspectable generic and consulting the type information statically known from the caller to make a decision on whether to use the runtimeclass name reported by the object or the statically known type.
- If the statically known type is implemented by the runtimeclass, the runtimeclass is still used to allow conversion to class types which would otherwise be not possible.  But if it isn't or the runtimeclass name is not a valid type, the static type is used instead.
- As part of making MarshalInspectable generic and passing the type information to CreateObject, we are also able to reduce QIs for scenarios where the runtimeclass name is misreported like DataPackage / DataPackageView.
- Added a cache for the custom attributes retrieved when unwrapping objects as getting the custom attribute was found to be expensive and the result was going to be the same each for time for a specific type.  This can probably be further improved for .NET 5 as mentioned in the issue, but it got tricky with composable types, so putting this fix out for now.

Resolves #360 
Contributes to #437

### CODE REVIEW

File: UnitTest/TestComponentCSharp_Tests.cs [hunk 1]
```diff
@@ -1773,5 +1783,15 @@ public void TestInterfaceObjectMarshalling()
 
             Assert.Equal(TestObject.ReadWriteProperty, nativeProperties.ReadWriteProperty);
         }
+
+        [Fact]
```
Comment (Scottj1s) [inline UnitTest/TestComponentCSharp_Tests.cs:1787]: what is this testing, related to generic MarshalInspectable?  can you add a comment?

File: WinRT.Runtime/ComWrappersSupport.cs [hunk 2]
```diff
@@ -328,6 +342,44 @@ private static bool IsIReferenceArray(Type implementationType)
             return CreateFactoryForImplementationType(runtimeClassName, implementationType);
         }
 
+        internal static string GetRuntimeClassForTypeCreation(IInspectable inspectable, Type staticallyDeterminedType)
+        {
+            string runtimeClassName = inspectable.GetRuntimeClassName(noThrow: true);
+            if (staticallyDeterminedType != null && staticallyDeterminedType != typeof(object))
+            {
+                // We have a static type which we can use to construct the object.  But, we can't just it for all scenarios
```
Comment (Scottj1s) [inline WinRT.Runtime/ComWrappersSupport.cs:350]: just use it

File: WinRT.Runtime/ComWrappersSupport.cs [hunk 3]
```diff
@@ -28,6 +28,7 @@ public static partial class ComWrappersSupport
     {
         private readonly static ConcurrentDictionary<string, Func<IInspectable, object>> TypedObjectFactoryCache = new ConcurrentDictionary<string, Func<IInspectable, object>>();
         private readonly static ConditionalWeakTable<object, object> CCWTable = new ConditionalWeakTable<object, object>();
+        private readonly static ConcurrentDictionary<Type, MemberInfo> TypeObjectRefFieldCache = new ConcurrentDictionary<Type, MemberInfo>();
```
Comment (Scottj1s) [inline WinRT.Runtime/ComWrappersSupport.cs:31]: is this Bartek's suggestion?

File: WinRT.Runtime/ComWrappersSupport.net5.cs [hunk 4]
```diff
@@ -50,26 +52,32 @@ internal static unsafe InspectableInfo GetInspectableInfo(IntPtr pThis)
...
-        public static object CreateRcwForComObject(IntPtr ptr)
+        public static T CreateRcwForComObject<T>(IntPtr ptr)
         {
             if (ptr == IntPtr.Zero)
             {
-                return null;
+                return default;
             }
 
+            if (typeof(T) != typeof(object))
```
Comment (Scottj1s) [inline WinRT.Runtime/ComWrappersSupport.net5.cs:62]: why the if check?

File: WinRT.Runtime/Projections/Uri.cs [hunk 5]
```diff
@@ -112,7 +112,7 @@ public static IObjectReference CreateMarshaler(global::System.Uri value)
                 return null;
             }
 
-            using var uri = ObjectReference<IUnknownVftbl>.FromAbi(ptr).As<ABI.Windows.Foundation.IUriRuntimeClassVftbl>();
+            using var uri = ObjectReference<ABI.Windows.Foundation.IUriRuntimeClassVftbl>.FromAbi(ptr);
```
Comment (Scottj1s) [inline WinRT.Runtime/Projections/Uri.cs:115]: workaround removed!

**Review by Scottj1s — APPROVED** [review]
looks good - just a few minor suggestions

File: WinRT.Runtime/ComWrappersSupport.cs (hunk 3 above)
Comment (manodasanW) [reply WinRT.Runtime/ComWrappersSupport.cs:31]: This is indeed an area where bartek saw high costs (retrieving custom attributes).  And one of the approaches we discussed was doing caching here to see if we can improve performance.

Comment (jkoritzinsky) [reply WinRT.Runtime/ComWrappersSupport.cs:31]: I still wonder if we can enhance `IWinRTObject` to avoid all of the reflection usage altogether (at least for the .NET 5.0 projection). That way we don't need to add another cache.

Comment (manodasanW) [reply WinRT.Runtime/ComWrappersSupport.cs:31]: I agree I think we should still look at if we can enhance IWinRTObject and eliminate it for .NET 5 which is why I am not closing the issue.  I got this change out for now as I wanted to get this PR out with some improvements as it was getting large, then do that as an additive thing when I got it working.

My initial attempt was trying to just use NativeObject from IWinRTObject as the result when a bool was set which is set in the classes which have objreferencewrapper but it broke in composable scenarios where a managed type implementing a projected type also had a NativeObject set but that wouldn't have been previously used.  I need to think about how to handle that scenario.  Was there any other enhancements you were thinking we need to make to IWinRTObject to achieve it and that may help with that issue?

File: WinRT.Runtime/ComWrappersSupport.cs [hunk 6]
```diff
@@ -328,6 +342,44 @@ private static bool IsIReferenceArray(Type implementationType)
             return CreateFactoryForImplementationType(runtimeClassName, implementationType);
         }
 
+        internal static string GetRuntimeClassForTypeCreation(IInspectable inspectable, Type staticallyDeterminedType)
+        {
+            string runtimeClassName = inspectable.GetRuntimeClassName(noThrow: true);
```
[the remark this answers is not in the document]
Comment (manodasanW) [reply WinRT.Runtime/ComWrappersSupport.cs:347]: If it throws, we return null and caller handles it by just using the iinspecatable rather than casting it to a type.  This is what we did for the .NET 5 projection before.  Looks like .NET standard 2 projection might have thrown before in this case, but I don't think that was intentional as they are also have logic to return iinspectable but runtimeclass name is null.

File: WinRT.Runtime/ComWrappersSupport.net5.cs (hunk 4 above)
Comment (manodasanW) [reply WinRT.Runtime/ComWrappersSupport.net5.cs:62]: Will remove as it is now redundant.  It also now check for it inside of GetRuntimeClassForTypeCreation.

File: WinRT.Runtime/ComWrappersSupport.cs (hunk 3 above)
Comment (jkoritzinsky) [reply WinRT.Runtime/ComWrappersSupport.cs:31]: One option would be to add a new `bool` property in `IWinRTObject` named `IsComposed`. By default, it would return `false`. We'd update the codegen for composable runtime classes so for a given class `Composable`, it is implemented as follows:

```csharp
bool IWinRTObject.IsComposed => this.GetType() != typeof(Composable);
```

Since each composable class would override this, calls to it would always used the most-derived implementation. Therefore, we'd correctly be able to detect if an object is composed (and if we can unwrap it).

Comment (manodasanW) [reply WinRT.Runtime/ComWrappersSupport.cs:31]: That is actually a clever idea and I think will work and looks like what we do in the constructor already for another thing.  Will give it a try.
