### PR TITLE
Fix diagnostics for namespaces with internal partial types

### LINKED ISSUE #1425: Error message for 'A public type has a namespace that shares no common prefix' doesn't specify the offending type
When using `<CsWinRTComponent>true</>` and tripping this error:

```
1>FooBar.cs(5,30,5,37): error CsWinRT1001: A public type has a namespace ('Foo.Bar.Baz') that shares no common prefix with other namespaces ('MyLibrary'). All types within a Windows Metadata file must exist in a sub namespace of the namespace that is implied by the file name. (https://github.com/microsoft/CsWinRT/tree/master/src/Authoring/WinRT.SourceGenerator/AnalyzerReleases.Unshipped.md)
```

It says what the namespace conflict is but doesn't give the right file/line number or tell me which type is the problem.

### PR DESCRIPTION
**Pull request by manodasanW**
The diagnostics analyzer for namespaces found all the namespaces which had public types and then made sure they are a subset of the one which the authored component is.  As part of determining public types, the check also considered partial types to be public with the assumption that it would later to be checked to figure out whether it is really public or not.  But for the namespace diagnostics this wasn't done as it is done in other scenarios.  In addition, partial types don't matter for namespace diagnostics as the diagnostics analyzer will see at least one of the partial types with its declared accessibility.  Due to that, this PR addresses this issue by making the namespace check only look for public types and not partial ones.

Fixes #1425

### CODE REVIEW

File: src/Authoring/WinRT.SourceGenerator/Generator.cs [hunk 1]
```diff
@@ -224,6 +224,10 @@ public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
             //   once from the namespace declaration and once from the member's declaration
             if (syntaxNode is NamespaceDeclarationSyntax @namespace)
             {
+                // We only include the namespace if it has a public type as otherwise it won't.
```
Comment (vineeththomasalex) [inline src/Authoring/WinRT.SourceGenerator/Generator.cs:227]: Nit 
```suggestion
                // We only include the namespace if it has a public type as otherwise it won't
```

**Review by vineeththomasalex — APPROVED** [review]
