### PR TITLE
Use `AppContext.BaseDirectory`

### LINKED ISSUE #992: WinRT file uses single file dangerous pattern
**Describe the bug**
The [WinRT.cs](https://github.com/microsoft/CsWinRT/blob/master/src/cswinrt/strings/WinRT.cs#L110) file uses an [API incompatibility pattern](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file#api-incompatibility) for single file, using Assembly.Location will return an empty string, making `_currentModuleDirectory` to be an empty string.

This file is later on imported into the WPF repository, see https://github.com/dotnet/wpf/issues/5226
In order to be able to enable the single file analyzer in the WPF repository, all the warnings need to be addressed. For now, I will suppress the warning in the WPF repository pointing to this issue, and once addressed the WPF repo can be updated.

**Expected behavior**
When a warning is flagged the different remediation options are:
- Suppress the warning when the behavior is expected and handled by the code, or the code is not relevant for single-file scenarios
- Mark the code as single file dangerous with the attribute [RequiresAssemblyFiles]
- Remediate the code to handle the single file case

**Additional context**
For additional context of single-file deployment see the [documentation](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file)

### PR DESCRIPTION
**Pull request by kant2002**
instead of `Assembly.GetExecutingAssembly().Location`.
I change this pattern in tests too, in case somebody would like to execute them after trimming or AOT context
Related #992

### CODE REVIEW

**Comment by manodasanW** [comment]
@kant2002 Thanks for addressing this.  I ran the pipeline and it looks like the following test failed.  Can you check if it passes for you or not?  Might be related to the trailing slash when appending filename.

**[xUnit.net 00:00:10.33]     UnitTest.TestCSharp.TestStorageFile [FAIL]**
  Failed UnitTest.TestCSharp.TestStorageFile [32 ms]
  Error Message:
   System.AggregateException : One or more errors occurred. (Value does not fall within the expected range.)
---- System.ArgumentException : Value does not fall within the expected range.
  Stack Trace:
     at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) in System.Private.CoreLib.dll:token 0x6002dd6+0x11
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) in System.Private.CoreLib.dll:token 0x6002df2+0x3f
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout) in System.Private.CoreLib.dll:token 0x6002df1+0x0
   at UnitTest.TestCSharp.TestStorageFile() in D:\a\1\s\src\Tests\UnitTest\TestComponentCSharp_Tests.cs:line 540
----- Inner Stack Trace -----
   at UnitTest.TestCSharp.TestStorageFileAsync() in D:\a\1\s\src\Tests\UnitTest\TestComponentCSharp_Tests.cs:line 532

File: src/Tests/UnitTest/TestComponentCSharp_Tests.cs [hunk 1]
```diff
@@ -528,7 +528,7 @@ public void TestBuffer()
 
         async Task TestStorageFileAsync()
         {
-            var folderPath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
+            var folderPath = AppContext.BaseDirectory;
             StorageFile file = await StorageFile.GetFileFromPathAsync(folderPath + "\\UnitTest.dll");
```
Comment (tlakollo) [inline src/Tests/UnitTest/TestComponentCSharp_Tests.cs:532]: This is the problematic line the AppContext.BaseDirectory already contains a forward slash at the end of the path, for example `cswinrt\src\Tests\unittest\bin\x64\Release\net6.0\` 
Changing the code to
```C#
StorageFile file = await StorageFile.GetFileFromPathAsync($"{folderPath}UnitTest.dll");
```
worked for me. 
Having said that I think we might need something to test even this same test storage test in single file mode. I think files like the Benchmarks.manifest will not be bundled and getting the base directory and then looking for the file will work. But I'm not completely sure about UnitTest.dll if it gets bundled along with the other dlls you might not find it.

File: src/cswinrt/strings/WinRT.cs [hunk 2]
```diff
@@ -107,7 +107,7 @@ internal class DllModule
         readonly DllGetActivationFactory _GetActivationFactory;
         readonly DllCanUnloadNow _CanUnloadNow; // TODO: Eventually periodically call
 
-        static readonly string _currentModuleDirectory = System.IO.Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location);
+        static readonly string _currentModuleDirectory = AppContext.BaseDirectory;
```
Comment (tlakollo) [inline src/cswinrt/strings/WinRT.cs:110]: I'm not fully sure if this is the right fix, in single-file mode the AppContext.BaseDirectory will point to the location of the single-file executable. Depending on how the `_currentModuleDirectory` is used later, the code could break which is why I opened the issue. If someone uses the `_currentModuleDirectory` to find stuff that got bundled in the `exe` that is going to break 
cc @agocke

File: src/Tests/UnitTest/TestComponentCSharp_Tests.cs (hunk 1 above)
Comment (kant2002) [reply src/Tests/UnitTest/TestComponentCSharp_Tests.cs:532]: Does `UnitTest.dll` used just because it happens to exists in the build of the test project? Maybe test can have some non-executable file which will be read. Or this code tests that executable file can be read?

File: src/cswinrt/strings/WinRT.cs (hunk 2 above)
Comment (kant2002) [reply src/cswinrt/strings/WinRT.cs:110]: The only usage for that variable is here
https://github.com/microsoft/CsWinRT/blob/755b8a77f32c566bbca7848cdb0275d915ad7bf0/src/cswinrt/strings/WinRT.cs#L133-L135

Which is just used to get `DllGetActivationFactory` from DLL. That's for fallback, if `RoGetActivationFactory` cannot find factory for the class. And you are prbably right, I'm too fast to apply fix here.

Do I properly understand that `DllGetActivationFactory` is created in DLL by WinRT-component vendor. In case if CsWinRT was used it is comes from here 
https://github.com/microsoft/CsWinRT/blob/ad6adcb997b40cea649cf4156451316e714bc3ea/src/Authoring/WinRT.Host/WinRT.Host.cpp#L300-L303

Short glance at the code indicates that it does not take into account single-file deployment at all. Do I see things correctly?

Comment (vitek-karas) [reply src/cswinrt/strings/WinRT.cs:110]: My understanding is that the code is loading a native dll from that path. Native dlls don't get bundled by default, so using the BaseDirectory will work in that case. Unfortunately if somebody specifies `IncludeNativeLibrariesForSelfExtract` the native dll will be bundled and then extracted into a "Temp" directory. But currently we don't provide a good way to find that directory - see https://github.com/dotnet/runtime/issues/43010.

I think one of the native library APIs should be able to try to load the library by a simple name (the same way `DllImport` does), which will find the library always, since the host correctly sets up `NATIVE_DLL_SEARCH_DIRECTORIES`. @elinor-fung Do you know which of the `NativeLibrary` APIs (if any) will trigger the normal runtime's "load library" behavior.

Comment (elinor-fung) [reply src/cswinrt/strings/WinRT.cs:110]: [`NativeLibrary.Load(string, Assembly, DllImportSearchPath?)`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.nativelibrary.load#System_Runtime_InteropServices_NativeLibrary_Load_System_String_System_Reflection_Assembly_System_Nullable_System_Runtime_InteropServices_DllImportSearchPath__)

Comment (kant2002) [reply src/cswinrt/strings/WinRT.cs:110]: I probably misled people a bit here by not showing subsequent code, with assumption that it would be inspected. See below.

https://github.com/microsoft/CsWinRT/blob/755b8a77f32c566bbca7848cdb0275d915ad7bf0/src/cswinrt/strings/WinRT.cs#L133-L141

shows that `Platform.LoadLibraryExW` used primarily for `NETSTANDARD2.0` or `NETCOREAPP2.0`, when on more modern platforms subsequently used `NativeLibrary.TryLoad` which is essentially same as what @elinor-fung proposed. If `dllImportSearchPath == null` trigger use `NATIVE_DLL_SEARCH_DIRECTORIES` then probably that's enough.

Only case which I think is left, is when somehow somebody would like to have "out-of-process" hosting with single-file package. That's `WinRT.Host.cpp` file is for which I mention in previous comments. Is this supported scenario?

Comment (vitek-karas) [reply src/cswinrt/strings/WinRT.cs:110]: Single-file is only supported for applications (exe), I would not expect out-of-proc hosted components to be built as applications (similar to COM host components, those are also classlib projects not apps). So that should already disqualify almost all such cases.

On top of that, hosting APIs (hostfxr) don't support single-file in any form currently, so even if the SDK would somehow build it, it won't run.

**Comment by kant2002** [comment]
@tlakollo do you have any other concerns? It seems that everything was sorted out in the end. Isn't it?

**Comment by tlakollo** [comment]
From what I read the scenario that uses Assembly.Location is not supported in single-file mode, so I'm fine with either the current change just run the CI and merge or leave the old code and just suppress the warning with the justification that mentions the code won't reach that path in single-file mode. Let me see if I have permission to run the pipeline which I doubt

**Comment by tlakollo** [comment]
@manodasanW can you trigger the pipeline run to verify the change doesn't break anything?

**Comment by kant2002** [comment]
Isn’t proper way would be start working on running single-file mode tests?
Or there already issue which tracks that?

**Comment by manodasanW** [comment]
@kant2002 I agree we should add some single file test scenarios to validate this.  From a quick look, it wasn't clear to me if we would be able to get our MSTest tests to run also in single file mode.  But we can probably have a console app consuming a CsWinRT test projection that publishes to single file and then run it in our test pass as a form of validating it.  Thoughts or any other suggestions?

**Comment by angelazhangmsft** [comment]
> Looks like all tests passed, but none of the tests I believe today exercise single file mode. We should try out a CsWinRT projection consumption scenario with single file mode and ensure that it works with these changes. @angelazhangmsft Angela Zhang (SHE/HER) FTE can you help out here trying this build with one of our console app samples?

Looks like the changes here enable CsWinRT projection consumption scenario with single file mode. We should address #999 before merging the PR

**Review by manodasanW — APPROVED** [review]

**Review by j0shuams — APPROVED** [review]

**Comment by kant2002** [comment]
Thanks you!
