### PR TITLE
Avoid generating duplicated symbols when patch method

### LINKED ISSUE #1173: IIDOptimizer produced lots of duplicated symbols
**Describe the bug**
IIDOptimizer doesn't check whether a symbol has been emitted, which result in producing lots of duplicated symbols.

**To Reproduce**
Let's decompile Microsoft.Windows.SDK.NET.dll with ILSpy:

image

image

image

**Expected behavior**
No duplicated symbols emitted.

**Version Info**
Windows App SDK 1.1-preview
CsWinRT 1.6.1
Microsoft.Windows.SDK.NET 10.0.19041.24

**Additional context**

### PR DESCRIPTION
**Pull request by hez2010**
Introduced a symbol cache to avoid symbols being re-generated.

Before:

image

image

image

After:

image

image

image

Fixes #1173

### CODE REVIEW

**Comment by hez2010** [comment]
Now it's ready for review.

File: src/Perf/IIDOptimizer/GuidPatcher.cs [hunk 1]
```diff
@@ -172,25 +174,35 @@ private bool PatchNonGenericTypeIID(MethodBody body, int startILIndex, TypeRefer
         private bool PatchGenericTypeIID(MethodBody body, int startILIndex, TypeReference type, int numberOfInstructionsToOverwrite)
         {
             SignaturePart rootSignaturePart = signatureGenerator.GetSignatureParts(type);
+            var methodName = $"<IIDData>{type.FullName}";
+            MethodReference guidDataMethodReference;
+            if (methodCache.ContainsKey(methodName))
+            {
+                guidDataMethodReference = methodCache[methodName];
+            }
+            else
```
Comment (jkotas) [inline src/Perf/IIDOptimizer/GuidPatcher.cs:183]: You can replace this with `if (!methodCache.TryGetValue(methodName, ... )) {`

Comment (hez2010) [reply src/Perf/IIDOptimizer/GuidPatcher.cs]: Done.

**Review by manodasanW — APPROVED** [review]

**Comment by manodasanW** [comment]
Thanks @hez2010 for this change.
