### PR TITLE
Fix authoring bugs

### LINKED ISSUE #693: Can't find NoiseAsset_256X256_PNG.png
1. Created a C# NET 5 class library. Reference the WinUI 3 Preview 4 CI 1/26 nuget package. 
2. Follow the authoring instructions to produce a nuget pkg for the class library
3. Created a cppwinrt WinUI 3 app from WinUI 3 Preview 3 VSIX 
4. update cppwinrt app's WinUI reference to latest internal WinUI nuget preview 4 from 01/26
5. Referenced the NET 5 class library nupkg file from the cppwinrt app via a local nuget source
6. Build solution

Workaround for now: create an empty png file at that location

### PR DESCRIPTION
**Pull request by j0shuams**
Previously, our targets that automate dll reference updating were too assumptive in what files would be in the authored nupkg. This PR introduces a filter on the dlls we package with an authored winmd/dll, as well as make some structural changes to remove warnings about the nupkg. Some bugs arose because of the assumption that only CsWinRT related dlls would be on our 
reference path when building, when in fact WinUI dlls/assets were being added just by nature of a package reference. 

I also found some things to cleanup in WinRTRules

Closes #693 #696 #697

### CODE REVIEW

File: src/Authoring/WinRT.SourceGenerator/WinRTRules.cs [hunk 1]
```diff
@@ -124,12 +124,6 @@ private static DiagnosticDescriptor MakeRule(string id, string title, string mes
             "Array signature found with multi-dimensional array, which is not a valid Windows Runtime type",
             "Method '{0}' has a multi-dimensional array of type '{1}' in its signature. Arrays in Windows Runtime method signatures must be one dimensional.");
```
Comment (manodasanW) [inline src/Authoring/WinRT.SourceGenerator/WinRTRules.cs:126]: Is this not needed?

Comment (j0shuams) [reply src/Authoring/WinRT.SourceGenerator/WinRTRules.cs:126]: No I used this at one point, but have switched to a more general "not valid type" rule, and this one has been unused for a while.

**Comment by j0shuams** [comment]
Wwhen testing with C# apps via package reference, there are some issues with the target framework of the consumer. Although the changes in the PR are aimed at support for native consumers, I won't push for this to merge until told otherwise and/or the issues with c# consumers are resolved.

**Review by manodasanW — APPROVED** [review]
